name: "IaC Cost Estimator"
description: "Estimates the cost of changes made in infrastructure-as-code (IaC)"

inputs:
    iac-stack:
        description: "The IaC stack to analyze (terraform, amplify-gen2, cdk, pulumi)"
        required: false
        default: "terraform"
    iac-dir:
        description: "Directory path where the IaC code resides"
        required: false
        default: ""

runs:
    using: "node20"
    main: "dist/index.js"
