name: IaC Cost Estimation

branding:
    icon: "server"
    color: "green"

on:
    pull_request:
        types: [opened, synchronize, reopened]

permissions:
    pull-requests: write
    contents: read

jobs:
    estimate-cost:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 2

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: "npm"

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3
              with:
                  terraform_version: "1.10.5"

            - name: Run Cost Estimation
              uses: ./
              with:
                  iac-stack: ${{ inputs.iac-stack || 'terraform' }}
                  iac-dir: ${{ inputs.iac-dir || '' }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
