name: IaC Cost Estimation

on:
    pull_request:
        types: [opened, synchronize, reopened]

permissions:
    pull-requests: write
    contents: read

jobs:
    estimate-cost:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 2

            - name: Run Cost Estimation
              uses: ./
